build: off

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\test\\tools\\run_with_env.cmd"
  matrix:
    - PYTHON: "C:\\Python26"
      TOXENV: "py26"
    - PYTHON: "C:\\Python26-x64"
      TOXENV: "py26"
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"
    - PYTHON: "C:\\Python27-x64"
      TOXENV: "py27"
    - PYTHON: "C:\\Python33"
      TOXENV: "py33"
    - PYTHON: "C:\\Python33-x64"
      TOXENV: "py33"
    - PYTHON: "C:\\Python34"
      TOXENV: "py34"
    - PYTHON: "C:\\Python34-x64"
      TOXENV: "py34"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
    - PYTHON: "C:\\Python35-x64"
      TOXENV: "py35"
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"
    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"
  fast_finish: true 

install:
  - ECHO "Powershell version:"
  - ps: "$PSVersionTable.PSVersion.Major"

  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & .\\test\\tools\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  
  # Check that we have the expected version and architecture for Python
  - "python --version"  
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install tox"

test_script:
  - "echo %CMD_IN_ENV%"
  - "set"
  - ps: "ls"
  - "echo %CMD_IN_ENV% tox -e %TOXENV%"
  - "%CMD_IN_ENV% tox"
  - "%CMD_IN_ENV% tox -e %TOXENV%"

on_success:
  - ".tox\\%TOXENV%\\Scripts\\activate"

branches:
  only:
    - master
